# Generated by Django 3.1.1 on 2020-11-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passanger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passanger',
            old_name='flight',
            new_name='flights',
        ),
    ]
